window.esdocSearchIndex = [
  [
    "pcl-free-pass/src/constants/routes.js~about",
    "variable/index.html#static-variable-ABOUT",
    "<span>ABOUT</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~add_vaccine_certificate",
    "variable/index.html#static-variable-ADD_VACCINE_CERTIFICATE",
    "<span>ADD_VACCINE_CERTIFICATE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/keys.js~app_lang",
    "variable/index.html#static-variable-APP_LANG",
    "<span>APP_LANG</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Keys.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~authenticated_route",
    "variable/index.html#static-variable-AUTHENTICATED_ROUTE",
    "<span>AUTHENTICATED_ROUTE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~authenticated_tab_route",
    "variable/index.html#static-variable-AUTHENTICATED_TAB_ROUTE",
    "<span>AUTHENTICATED_TAB_ROUTE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~auth_flow_route",
    "variable/index.html#static-variable-AUTH_FLOW_ROUTE",
    "<span>AUTH_FLOW_ROUTE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~auth_route",
    "variable/index.html#static-variable-AUTH_ROUTE",
    "<span>AUTH_ROUTE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/config/i18nextconfig.js~available_languages",
    "variable/index.html#static-variable-AVAILABLE_LANGUAGES",
    "<span>AVAILABLE_LANGUAGES</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/i18nextConfig.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/root/app.js~app",
    "function/index.html#static-function-App",
    "<span>App</span> <span class=\"search-result-import-path\">pcl-free-pass/src/root/App.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/colors.js~appcolor",
    "variable/index.html#static-variable-AppColor",
    "<span>AppColor</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Colors.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/navigation/auth.js~auth",
    "function/index.html#static-function-Auth",
    "<span>Auth</span> <span class=\"search-result-import-path\">pcl-free-pass/src/navigation/Auth.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/navigation/authenticated.js~authenticated",
    "function/index.html#static-function-Authenticated",
    "<span>Authenticated</span> <span class=\"search-result-import-path\">pcl-free-pass/src/navigation/Authenticated.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/navigation/authenticatedtabnavigator.js~authenticatedtabs",
    "function/index.html#static-function-AuthenticatedTabs",
    "<span>AuthenticatedTabs</span> <span class=\"search-result-import-path\">pcl-free-pass/src/navigation/AuthenticatedTabNavigator.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/button.js~button",
    "function/index.html#static-function-Button",
    "<span>Button</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Button.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/buttonlight.js~buttonlight",
    "function/index.html#static-function-ButtonLight",
    "<span>ButtonLight</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/ButtonLight.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~change_language",
    "variable/index.html#static-variable-CHANGE_LANGUAGE",
    "<span>CHANGE_LANGUAGE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~change_password",
    "variable/index.html#static-variable-CHANGE_PASSWORD",
    "<span>CHANGE_PASSWORD</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~change_password_url",
    "variable/index.html#static-variable-CHANGE_PASSWORD_URL",
    "<span>CHANGE_PASSWORD_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~checked_in_users",
    "variable/index.html#static-variable-CHECKED_IN_USERS",
    "<span>CHECKED_IN_USERS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~check_results",
    "variable/index.html#static-variable-CHECK_RESULTS",
    "<span>CHECK_RESULTS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~check_user",
    "variable/index.html#static-variable-CHECK_USER",
    "<span>CHECK_USER</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~choose_test",
    "variable/index.html#static-variable-CHOOSE_TEST",
    "<span>CHOOSE_TEST</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~common_routes",
    "variable/index.html#static-variable-COMMON_ROUTES",
    "<span>COMMON_ROUTES</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~confirm_image",
    "variable/index.html#static-variable-CONFIRM_IMAGE",
    "<span>CONFIRM_IMAGE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~confirm_test",
    "variable/index.html#static-variable-CONFIRM_TEST",
    "<span>CONFIRM_TEST</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~confirm_vaccine",
    "variable/index.html#static-variable-CONFIRM_VACCINE",
    "<span>CONFIRM_VACCINE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~contact_us",
    "variable/index.html#static-variable-CONTACT_US",
    "<span>CONTACT_US</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/navigation/commonstack.js~commonstack",
    "function/index.html#static-function-CommonStack",
    "<span>CommonStack</span> <span class=\"search-result-import-path\">pcl-free-pass/src/navigation/CommonStack.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/store/index.js~configurestore",
    "function/index.html#static-function-ConfigureStore",
    "<span>ConfigureStore</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/store/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/auth/confirmimage/index.js~confirmimage",
    "function/index.html#static-function-ConfirmImage",
    "<span>ConfirmImage</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/auth/confirmImage/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/contactus/index.js~contactus",
    "function/index.html#static-function-ContactUs",
    "<span>ContactUs</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/contactUs/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~download_page",
    "variable/index.html#static-variable-DOWNLOAD_PAGE",
    "<span>DOWNLOAD_PAGE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~drawer_route",
    "variable/index.html#static-variable-DRAWER_ROUTE",
    "<span>DRAWER_ROUTE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/components/dosesbottomsheet.js~dosesbottomsheet",
    "function/index.html#static-function-DosesBottomSheet",
    "<span>DosesBottomSheet</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/DosesBottomSheet.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~faq",
    "variable/index.html#static-variable-FAQ",
    "<span>FAQ</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~forgot_password",
    "variable/index.html#static-variable-FORGOT_PASSWORD",
    "<span>FORGOT_PASSWORD</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~forgot_password_url",
    "variable/index.html#static-variable-FORGOT_PASSWORD_URL",
    "<span>FORGOT_PASSWORD_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/faq/index.js~faq",
    "function/index.html#static-function-Faq",
    "<span>Faq</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/faq/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/auth/forgotpassword/index.js~forgotpassword",
    "function/index.html#static-function-ForgotPassword",
    "<span>ForgotPassword</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/auth/forgotPassword/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~get_btm",
    "variable/index.html#static-variable-GET_BTM",
    "<span>GET_BTM</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~get_manager_info",
    "variable/index.html#static-variable-GET_MANAGER_INFO",
    "<span>GET_MANAGER_INFO</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~get_tests",
    "variable/index.html#static-variable-GET_TESTS",
    "<span>GET_TESTS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~get_vaccines",
    "variable/index.html#static-variable-GET_VACCINES",
    "<span>GET_VACCINES</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~get_visited_places",
    "variable/index.html#static-variable-GET_VISITED_PLACES",
    "<span>GET_VISITED_PLACES</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/apirequests.js~getrequest",
    "function/index.html#static-function-GetRequest",
    "<span>GetRequest</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/apiRequests.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/headerlight.js~headerlight",
    "function/index.html#static-function-Headerlight",
    "<span>Headerlight</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Headerlight.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~image_results_extraction_url",
    "variable/index.html#static-variable-IMAGE_RESULTS_EXTRACTION_URL",
    "<span>IMAGE_RESULTS_EXTRACTION_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~import_test",
    "variable/index.html#static-variable-IMPORT_TEST",
    "<span>IMPORT_TEST</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~import_vaccine",
    "variable/index.html#static-variable-IMPORT_VACCINE",
    "<span>IMPORT_VACCINE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/components/indicator.js~indicator",
    "function/index.html#static-function-Indicator",
    "<span>Indicator</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Indicator.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/input.js~input",
    "function/index.html#static-function-Input",
    "<span>Input</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Input.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/bottomsheet.js~item",
    "function/index.html#static-function-Item",
    "<span>Item</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/BottomSheet.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/item.js~item",
    "function/index.html#static-function-Item",
    "<span>Item</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Item.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~loading_splash",
    "variable/index.html#static-variable-LOADING_SPLASH",
    "<span>LOADING_SPLASH</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/screens/common/loadingsplash/index.js~loadingsplash",
    "function/index.html#static-function-LoadingSplash",
    "<span>LoadingSplash</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/common/loadingSplash/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/config/pushnotifications.js~localnotification",
    "function/index.html#static-function-LocalNotification",
    "<span>LocalNotification</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/pushNotifications.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/keys.js~message",
    "variable/index.html#static-variable-MESSAGE",
    "<span>MESSAGE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Keys.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~my_info",
    "variable/index.html#static-variable-MY_INFO",
    "<span>MY_INFO</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~my_pass",
    "variable/index.html#static-variable-MY_PASS",
    "<span>MY_PASS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~my_profile",
    "variable/index.html#static-variable-MY_PROFILE",
    "<span>MY_PROFILE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/components/bottomsheet.js~modalbox",
    "function/index.html#static-function-ModalBox",
    "<span>ModalBox</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/BottomSheet.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/indicatorr.js~modalbox",
    "function/index.html#static-function-ModalBox",
    "<span>ModalBox</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Indicatorr.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/modalbox.js~modalbox",
    "function/index.html#static-function-ModalBox",
    "<span>ModalBox</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/ModalBox.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/resultmodal.js~modalbox",
    "function/index.html#static-function-ModalBox",
    "<span>ModalBox</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/ResultModal.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/myprofile/index.js~myprofile",
    "function/index.html#static-function-MyProfile",
    "<span>MyProfile</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/myProfile/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/noconnectionmodal.js~noconnectionmodal",
    "function/index.html#static-function-NoConnectionModal",
    "<span>NoConnectionModal</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/NoConnectionModal.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~pass_service",
    "variable/index.html#static-variable-PASS_SERVICE",
    "<span>PASS_SERVICE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~pass_service_url",
    "variable/index.html#static-variable-PASS_SERVICE_URL",
    "<span>PASS_SERVICE_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/apirequests.js~postrequest",
    "function/index.html#static-function-PostRequest",
    "<span>PostRequest</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/apiRequests.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~register_site",
    "variable/index.html#static-variable-REGISTER_SITE",
    "<span>REGISTER_SITE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~reset_password",
    "variable/index.html#static-variable-RESET_PASSWORD",
    "<span>RESET_PASSWORD</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~reset_password_url",
    "variable/index.html#static-variable-RESET_PASSWORD_URL",
    "<span>RESET_PASSWORD_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~results",
    "variable/index.html#static-variable-RESULTS",
    "<span>RESULTS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~results_routes",
    "variable/index.html#static-variable-RESULTS_ROUTES",
    "<span>RESULTS_ROUTES</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/index.js~results",
    "function/index.html#static-function-Results",
    "<span>Results</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/navigation/resultsstack.js~resultsstack",
    "function/index.html#static-function-ResultsStack",
    "<span>ResultsStack</span> <span class=\"search-result-import-path\">pcl-free-pass/src/navigation/ResultsStack.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~save_pcr",
    "variable/index.html#static-variable-SAVE_PCR",
    "<span>SAVE_PCR</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~save_self_test_data",
    "variable/index.html#static-variable-SAVE_SELF_TEST_DATA",
    "<span>SAVE_SELF_TEST_DATA</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~save_self_test_photo",
    "variable/index.html#static-variable-SAVE_SELF_TEST_PHOTO",
    "<span>SAVE_SELF_TEST_PHOTO</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~save_self_test_video",
    "variable/index.html#static-variable-SAVE_SELF_TEST_VIDEO",
    "<span>SAVE_SELF_TEST_VIDEO</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~save_sms_logs",
    "variable/index.html#static-variable-SAVE_SMS_LOGS",
    "<span>SAVE_SMS_LOGS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~settings",
    "variable/index.html#static-variable-SETTINGS",
    "<span>SETTINGS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~settings_routes",
    "variable/index.html#static-variable-SETTINGS_ROUTES",
    "<span>SETTINGS_ROUTES</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_current_user",
    "variable/index.html#static-variable-SET_CURRENT_USER",
    "<span>SET_CURRENT_USER</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_hospital_name",
    "variable/index.html#static-variable-SET_HOSPITAL_NAME",
    "<span>SET_HOSPITAL_NAME</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~set_image",
    "variable/index.html#static-variable-SET_IMAGE",
    "<span>SET_IMAGE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_loading",
    "variable/index.html#static-variable-SET_LOADING",
    "<span>SET_LOADING</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_notifications",
    "variable/index.html#static-variable-SET_NOTIFICATIONS",
    "<span>SET_NOTIFICATIONS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~set_password",
    "variable/index.html#static-variable-SET_PASSWORD",
    "<span>SET_PASSWORD</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_registered_site",
    "variable/index.html#static-variable-SET_REGISTERED_SITE",
    "<span>SET_REGISTERED_SITE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_result",
    "variable/index.html#static-variable-SET_RESULT",
    "<span>SET_RESULT</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_token",
    "variable/index.html#static-variable-SET_TOKEN",
    "<span>SET_TOKEN</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/redux/type/index.js~set_vaccine",
    "variable/index.html#static-variable-SET_VACCINE",
    "<span>SET_VACCINE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/type/index.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~sign_in",
    "variable/index.html#static-variable-SIGN_IN",
    "<span>SIGN_IN</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~sign_in_url",
    "variable/index.html#static-variable-SIGN_IN_URL",
    "<span>SIGN_IN_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~sign_up",
    "variable/index.html#static-variable-SIGN_UP",
    "<span>SIGN_UP</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~sign_up_screen",
    "variable/index.html#static-variable-SIGN_UP_SCREEN",
    "<span>SIGN_UP_SCREEN</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~sign_up_url",
    "variable/index.html#static-variable-SIGN_UP_URL",
    "<span>SIGN_UP_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~site_checkin",
    "variable/index.html#static-variable-SITE_CHECKIN",
    "<span>SITE_CHECKIN</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~site_info",
    "variable/index.html#static-variable-SITE_INFO",
    "<span>SITE_INFO</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~site_info_edit",
    "variable/index.html#static-variable-SITE_INFO_EDIT",
    "<span>SITE_INFO_EDIT</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~site_manager",
    "variable/index.html#static-variable-SITE_MANAGER",
    "<span>SITE_MANAGER</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~site_manager_routes",
    "variable/index.html#static-variable-SITE_MANAGER_ROUTES",
    "<span>SITE_MANAGER_ROUTES</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~socket_url",
    "variable/index.html#static-variable-SOCKET_URL",
    "<span>SOCKET_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/confirmselftest/index.js~stconfirmtest",
    "function/index.html#static-function-STConfirmTest",
    "<span>STConfirmTest</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/confirmSelfTest/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen1.js~stintroscreen1",
    "function/index.html#static-function-STIntroScreen1",
    "<span>STIntroScreen1</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen1.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen2.js~stintroscreen2",
    "function/index.html#static-function-STIntroScreen2",
    "<span>STIntroScreen2</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen2.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen3.js~stintroscreen3",
    "function/index.html#static-function-STIntroScreen3",
    "<span>STIntroScreen3</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen3.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen4.js~stintroscreen4",
    "function/index.html#static-function-STIntroScreen4",
    "<span>STIntroScreen4</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen4.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen5.js~stintroscreen5",
    "function/index.html#static-function-STIntroScreen5",
    "<span>STIntroScreen5</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen5.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen6.js~stintroscreen6",
    "function/index.html#static-function-STIntroScreen6",
    "<span>STIntroScreen6</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen6.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen7.js~stintroscreen7",
    "function/index.html#static-function-STIntroScreen7",
    "<span>STIntroScreen7</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen7.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/instructions/stintroscreen8.js~stintroscreen8",
    "function/index.html#static-function-STIntroScreen8",
    "<span>STIntroScreen8</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen8.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/stqrscanner.js~stqrscanner",
    "function/index.html#static-function-STQRScanner",
    "<span>STQRScanner</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/STQRScanner.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/selftesting/takephotostart/index.js~sttakephoto",
    "function/index.html#static-function-STTakePhoto",
    "<span>STTakePhoto</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/selfTesting/takePhotoStart/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_confirm_test",
    "variable/index.html#static-variable-ST_CONFIRM_TEST",
    "<span>ST_CONFIRM_TEST</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_introduction",
    "variable/index.html#static-variable-ST_INTRODUCTION",
    "<span>ST_INTRODUCTION</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_qr_code_scan",
    "variable/index.html#static-variable-ST_QR_CODE_SCAN",
    "<span>ST_QR_CODE_SCAN</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_record_video",
    "variable/index.html#static-variable-ST_RECORD_VIDEO",
    "<span>ST_RECORD_VIDEO</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_start_test",
    "variable/index.html#static-variable-ST_START_TEST",
    "<span>ST_START_TEST</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_start_timer",
    "variable/index.html#static-variable-ST_START_TIMER",
    "<span>ST_START_TIMER</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_take_photo",
    "variable/index.html#static-variable-ST_TAKE_PHOTO",
    "<span>ST_TAKE_PHOTO</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_test_results",
    "variable/index.html#static-variable-ST_TEST_RESULTS",
    "<span>ST_TEST_RESULTS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~st_upload_screen",
    "variable/index.html#static-variable-ST_UPLOAD_SCREEN",
    "<span>ST_UPLOAD_SCREEN</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~success",
    "variable/index.html#static-variable-SUCCESS",
    "<span>SUCCESS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~success_test",
    "variable/index.html#static-variable-SUCCESS_TEST",
    "<span>SUCCESS_TEST</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/components/separator.js~separator",
    "function/index.html#static-function-Separator",
    "<span>Separator</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Separator.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/auth/setpassword/index.js~setpassword",
    "function/index.html#static-function-SetPassword",
    "<span>SetPassword</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/auth/setPassword/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/navigation/settingsstack.js~settingsstack",
    "function/index.html#static-function-SettingsStack",
    "<span>SettingsStack</span> <span class=\"search-result-import-path\">pcl-free-pass/src/navigation/SettingsStack.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/auth/signup/index.js~signup",
    "function/index.html#static-function-SignUp",
    "<span>SignUp</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/auth/signUp/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/navigation/sitemanagerstack.js~sitemanagerstack",
    "function/index.html#static-function-SiteManagerStack",
    "<span>SiteManagerStack</span> <span class=\"search-result-import-path\">pcl-free-pass/src/navigation/SiteManagerStack.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/spinner.js~spinner",
    "function/index.html#static-function-Spinner",
    "<span>Spinner</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Spinner.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/auth/success/index.js~success",
    "function/index.html#static-function-Success",
    "<span>Success</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/auth/success/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/results/success/index.js~success",
    "function/index.html#static-function-Success",
    "<span>Success</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/results/success/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/success/index.js~success",
    "function/index.html#static-function-Success",
    "<span>Success</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/success/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~telegram_url",
    "variable/index.html#static-variable-TELEGRAM_URL",
    "<span>TELEGRAM_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~terms_conditions",
    "variable/index.html#static-variable-TERMS_CONDITIONS",
    "<span>TERMS_CONDITIONS</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~text_results_extraction_url",
    "variable/index.html#static-variable-TEXT_RESULTS_EXTRACTION_URL",
    "<span>TEXT_RESULTS_EXTRACTION_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/keys.js~token",
    "variable/index.html#static-variable-TOKEN",
    "<span>TOKEN</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Keys.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/myprofile/tabs/index.js~tabviewexample",
    "function/index.html#static-function-TabViewExample",
    "<span>TabViewExample</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/myProfile/tabs/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/screens/authenticated/termsandconditions/index.js~termsandconditions",
    "function/index.html#static-function-TermsAndConditions",
    "<span>TermsAndConditions</span> <span class=\"search-result-import-path\">pcl-free-pass/src/screens/authenticated/termsAndConditions/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/components/toast.js~toast",
    "function/index.html#static-function-Toast",
    "<span>Toast</span> <span class=\"search-result-import-path\">pcl-free-pass/src/components/Toast.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/toasttypes.js~toasttypes",
    "variable/index.html#static-variable-ToastTypes",
    "<span>ToastTypes</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ToastTypes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~update_profile_url",
    "variable/index.html#static-variable-UPDATE_PROFILE_URL",
    "<span>UPDATE_PROFILE_URL</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/apiroutes.js~update_site",
    "variable/index.html#static-variable-UPDATE_SITE",
    "<span>UPDATE_SITE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/ApiRoutes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/keys.js~user_data",
    "variable/index.html#static-variable-USER_DATA",
    "<span>USER_DATA</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Keys.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~vaccine_certificate",
    "variable/index.html#static-variable-VACCINE_CERTIFICATE",
    "<span>VACCINE_CERTIFICATE</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/routes.js~verify_otp",
    "variable/index.html#static-variable-VERIFY_OTP",
    "<span>VERIFY_OTP</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Routes.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/checkpermissions.js~checkstoragewrittingpermissions",
    "function/index.html#static-function-checkStorageWrittingPermissions",
    "<span>checkStorageWrittingPermissions</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/checkPermissions.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/regex.js~countrycodesregex",
    "variable/index.html#static-variable-countryCodesRegex",
    "<span>countryCodesRegex</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Regex.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/detecttextlanguage.js~detecttextlanguage",
    "function/index.html#static-function-detectTextLanguage",
    "<span>detectTextLanguage</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/detectTextLanguage.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/utils/getbuilddetails.js~getbuildinfo",
    "function/index.html#static-function-getBuildInfo",
    "<span>getBuildInfo</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/getBuildDetails.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/utils/asyncrequests.js~getdata",
    "function/index.html#static-function-getData",
    "<span>getData</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/asyncRequests.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/utils/getdeviceinfo.js~getdeviceinfo",
    "function/index.html#static-function-getDeviceInfo",
    "<span>getDeviceInfo</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/getDeviceInfo.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/institutionsdata.js~institutionsdata",
    "variable/index.html#static-variable-institutionsData",
    "<span>institutionsData</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/InstitutionsData.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/numberformatting.js~kmbtformatter",
    "function/index.html#static-function-kmbtFormatter",
    "<span>kmbtFormatter</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/numberFormatting.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/images.js~logo",
    "variable/index.html#static-variable-logo",
    "<span>logo</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Images.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/numberformatting.js~nformatter",
    "function/index.html#static-function-nFormatter",
    "<span>nFormatter</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/numberFormatting.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithlogo",
    "variable/index.html#static-variable-navigationOptionsWithLogo",
    "<span>navigationOptionsWithLogo</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithlogoandeditprofile",
    "function/index.html#static-function-navigationOptionsWithLogoAndEditProfile",
    "<span>navigationOptionsWithLogoAndEditProfile</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithlogoandhelp",
    "function/index.html#static-function-navigationOptionsWithLogoAndHelp",
    "<span>navigationOptionsWithLogoAndHelp</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithlogocustombackaction",
    "function/index.html#static-function-navigationOptionsWithLogoCustomBackAction",
    "<span>navigationOptionsWithLogoCustomBackAction</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithlogoonly",
    "variable/index.html#static-variable-navigationOptionsWithLogoOnly",
    "<span>navigationOptionsWithLogoOnly</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithlogowithoutback",
    "variable/index.html#static-variable-navigationOptionsWithLogoWithoutBack",
    "<span>navigationOptionsWithLogoWithoutBack</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithtitle",
    "function/index.html#static-function-navigationOptionsWithTitle",
    "<span>navigationOptionsWithTitle</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/config/navigationoptions.js~navigationoptionswithtransparentheader",
    "function/index.html#static-function-navigationOptionsWithTransparentHeader",
    "<span>navigationOptionsWithTransparentHeader</span> <span class=\"search-result-import-path\">pcl-free-pass/src/config/navigationOptions.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/regex.js~negativekeyworddetect",
    "variable/index.html#static-variable-negativeKeywordDetect",
    "<span>negativeKeywordDetect</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Regex.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/regex.js~orgnamepatternmatch",
    "variable/index.html#static-variable-orgNamePatternMatch",
    "<span>orgNamePatternMatch</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Regex.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/regex.js~pcrkeywordsmatch",
    "variable/index.html#static-variable-pcrKeywordsMatch",
    "<span>pcrKeywordsMatch</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Regex.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/asyncrequests.js~removedata",
    "function/index.html#static-function-removeData",
    "<span>removeData</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/asyncRequests.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/utils/asyncrequests.js~savedata",
    "function/index.html#static-function-saveData",
    "<span>saveData</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/asyncRequests.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~setcurrentuser",
    "function/index.html#static-function-setCurrentUser",
    "<span>setCurrentUser</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~sethospitalnamer",
    "function/index.html#static-function-setHospitalNameR",
    "<span>setHospitalNameR</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~setloader",
    "function/index.html#static-function-setLoader",
    "<span>setLoader</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~setnotifications",
    "function/index.html#static-function-setNotifications",
    "<span>setNotifications</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~setregisteredsite",
    "function/index.html#static-function-setRegisteredSite",
    "<span>setRegisteredSite</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~setresults",
    "function/index.html#static-function-setResults",
    "<span>setResults</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~settoken",
    "function/index.html#static-function-setToken",
    "<span>setToken</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/actions/user/index.js~setvaccine",
    "function/index.html#static-function-setVaccine",
    "<span>setVaccine</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/actions/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/constants/regex.js~smscontentdateget",
    "variable/index.html#static-variable-smsContentDateGet",
    "<span>smsContentDateGet</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Regex.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/constants/regex.js~smscontenttimeget",
    "variable/index.html#static-variable-smsContentTimeGet",
    "<span>smsContentTimeGet</span> <span class=\"search-result-import-path\">pcl-free-pass/src/constants/Regex.js</span>",
    "variable"
  ],
  [
    "pcl-free-pass/src/utils/react-redux-hooks.js~usedispatch",
    "function/index.html#static-function-useDispatch",
    "<span>useDispatch</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/react-redux-hooks.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/utils/react-redux-hooks.js~useselector",
    "function/index.html#static-function-useSelector",
    "<span>useSelector</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/react-redux-hooks.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/customhooks/user.js~usesignin",
    "function/index.html#static-function-useSignin",
    "<span>useSignin</span> <span class=\"search-result-import-path\">pcl-free-pass/src/customHooks/user.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/customhooks/user.js~usesignup",
    "function/index.html#static-function-useSignup",
    "<span>useSignup</span> <span class=\"search-result-import-path\">pcl-free-pass/src/customHooks/user.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/redux/reducers/user/index.js~userreducer",
    "function/index.html#static-function-userReducer",
    "<span>userReducer</span> <span class=\"search-result-import-path\">pcl-free-pass/src/redux/reducers/user/index.js</span>",
    "function"
  ],
  [
    "pcl-free-pass/src/utils/apirequests.js~xhrpostrequest",
    "function/index.html#static-function-xhrPostRequest",
    "<span>xhrPostRequest</span> <span class=\"search-result-import-path\">pcl-free-pass/src/utils/apiRequests.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/components/bottomsheet.js",
    "file/src/components/BottomSheet.js.html",
    "src/components/BottomSheet.js",
    "file"
  ],
  [
    "src/components/button.js",
    "file/src/components/Button.js.html",
    "src/components/Button.js",
    "file"
  ],
  [
    "src/components/buttonlight.js",
    "file/src/components/ButtonLight.js.html",
    "src/components/ButtonLight.js",
    "file"
  ],
  [
    "src/components/dosesbottomsheet.js",
    "file/src/components/DosesBottomSheet.js.html",
    "src/components/DosesBottomSheet.js",
    "file"
  ],
  [
    "src/components/headerlight.js",
    "file/src/components/Headerlight.js.html",
    "src/components/Headerlight.js",
    "file"
  ],
  [
    "src/components/indicator.js",
    "file/src/components/Indicator.js.html",
    "src/components/Indicator.js",
    "file"
  ],
  [
    "src/components/indicatorr.js",
    "file/src/components/Indicatorr.js.html",
    "src/components/Indicatorr.js",
    "file"
  ],
  [
    "src/components/input.js",
    "file/src/components/Input.js.html",
    "src/components/Input.js",
    "file"
  ],
  [
    "src/components/item.js",
    "file/src/components/Item.js.html",
    "src/components/Item.js",
    "file"
  ],
  [
    "src/components/modalbox.js",
    "file/src/components/ModalBox.js.html",
    "src/components/ModalBox.js",
    "file"
  ],
  [
    "src/components/noconnectionmodal.js",
    "file/src/components/NoConnectionModal.js.html",
    "src/components/NoConnectionModal.js",
    "file"
  ],
  [
    "src/components/resultmodal.js",
    "file/src/components/ResultModal.js.html",
    "src/components/ResultModal.js",
    "file"
  ],
  [
    "src/components/stqrscanner.js",
    "file/src/components/STQRScanner.js.html",
    "src/components/STQRScanner.js",
    "file"
  ],
  [
    "src/components/separator.js",
    "file/src/components/Separator.js.html",
    "src/components/Separator.js",
    "file"
  ],
  [
    "src/components/spinner.js",
    "file/src/components/Spinner.js.html",
    "src/components/Spinner.js",
    "file"
  ],
  [
    "src/components/toast.js",
    "file/src/components/Toast.js.html",
    "src/components/Toast.js",
    "file"
  ],
  [
    "src/config/i18nextconfig.js",
    "file/src/config/i18nextConfig.js.html",
    "src/config/i18nextConfig.js",
    "file"
  ],
  [
    "src/config/navigationoptions.js",
    "file/src/config/navigationOptions.js.html",
    "src/config/navigationOptions.js",
    "file"
  ],
  [
    "src/config/pushnotifications.js",
    "file/src/config/pushNotifications.js.html",
    "src/config/pushNotifications.js",
    "file"
  ],
  [
    "src/constants/apiroutes.js",
    "file/src/constants/ApiRoutes.js.html",
    "src/constants/ApiRoutes.js",
    "file"
  ],
  [
    "src/constants/colors.js",
    "file/src/constants/Colors.js.html",
    "src/constants/Colors.js",
    "file"
  ],
  [
    "src/constants/images.js",
    "file/src/constants/Images.js.html",
    "src/constants/Images.js",
    "file"
  ],
  [
    "src/constants/institutionsdata.js",
    "file/src/constants/InstitutionsData.js.html",
    "src/constants/InstitutionsData.js",
    "file"
  ],
  [
    "src/constants/keys.js",
    "file/src/constants/Keys.js.html",
    "src/constants/Keys.js",
    "file"
  ],
  [
    "src/constants/regex.js",
    "file/src/constants/Regex.js.html",
    "src/constants/Regex.js",
    "file"
  ],
  [
    "src/constants/routes.js",
    "file/src/constants/Routes.js.html",
    "src/constants/Routes.js",
    "file"
  ],
  [
    "src/constants/toasttypes.js",
    "file/src/constants/ToastTypes.js.html",
    "src/constants/ToastTypes.js",
    "file"
  ],
  [
    "src/constants/golbal.js",
    "file/src/constants/golbal.js.html",
    "src/constants/golbal.js",
    "file"
  ],
  [
    "src/customhooks/user.js",
    "file/src/customHooks/user.js.html",
    "src/customHooks/user.js",
    "file"
  ],
  [
    "src/headlesstasks/qrchanger.js",
    "file/src/headlessTasks/qrChanger.js.html",
    "src/headlessTasks/qrChanger.js",
    "file"
  ],
  [
    "src/i18n/ar/about.js",
    "file/src/i18n/ar/about.js.html",
    "src/i18n/ar/about.js",
    "file"
  ],
  [
    "src/i18n/ar/buttons.js",
    "file/src/i18n/ar/buttons.js.html",
    "src/i18n/ar/buttons.js",
    "file"
  ],
  [
    "src/i18n/ar/changelanguage.js",
    "file/src/i18n/ar/changeLanguage.js.html",
    "src/i18n/ar/changeLanguage.js",
    "file"
  ],
  [
    "src/i18n/ar/changepassword.js",
    "file/src/i18n/ar/changePassword.js.html",
    "src/i18n/ar/changePassword.js",
    "file"
  ],
  [
    "src/i18n/ar/common.js",
    "file/src/i18n/ar/common.js.html",
    "src/i18n/ar/common.js",
    "file"
  ],
  [
    "src/i18n/ar/contactus.js",
    "file/src/i18n/ar/contactUs.js.html",
    "src/i18n/ar/contactUs.js",
    "file"
  ],
  [
    "src/i18n/ar/faq.js",
    "file/src/i18n/ar/faq.js.html",
    "src/i18n/ar/faq.js",
    "file"
  ],
  [
    "src/i18n/ar/index.js",
    "file/src/i18n/ar/index.js.html",
    "src/i18n/ar/index.js",
    "file"
  ],
  [
    "src/i18n/ar/login.js",
    "file/src/i18n/ar/login.js.html",
    "src/i18n/ar/login.js",
    "file"
  ],
  [
    "src/i18n/ar/myinfo.js",
    "file/src/i18n/ar/myInfo.js.html",
    "src/i18n/ar/myInfo.js",
    "file"
  ],
  [
    "src/i18n/ar/mypass.js",
    "file/src/i18n/ar/myPass.js.html",
    "src/i18n/ar/myPass.js",
    "file"
  ],
  [
    "src/i18n/ar/myprofile.js",
    "file/src/i18n/ar/myProfile.js.html",
    "src/i18n/ar/myProfile.js",
    "file"
  ],
  [
    "src/i18n/ar/notifications.js",
    "file/src/i18n/ar/notifications.js.html",
    "src/i18n/ar/notifications.js",
    "file"
  ],
  [
    "src/i18n/ar/results.js",
    "file/src/i18n/ar/results.js.html",
    "src/i18n/ar/results.js",
    "file"
  ],
  [
    "src/i18n/ar/setting.js",
    "file/src/i18n/ar/setting.js.html",
    "src/i18n/ar/setting.js",
    "file"
  ],
  [
    "src/i18n/ar/signup.js",
    "file/src/i18n/ar/signup.js.html",
    "src/i18n/ar/signup.js",
    "file"
  ],
  [
    "src/i18n/ar/sitemanager.js",
    "file/src/i18n/ar/siteManager.js.html",
    "src/i18n/ar/siteManager.js",
    "file"
  ],
  [
    "src/i18n/ar/terms.js",
    "file/src/i18n/ar/terms.js.html",
    "src/i18n/ar/terms.js",
    "file"
  ],
  [
    "src/i18n/de/about.js",
    "file/src/i18n/de/about.js.html",
    "src/i18n/de/about.js",
    "file"
  ],
  [
    "src/i18n/de/buttons.js",
    "file/src/i18n/de/buttons.js.html",
    "src/i18n/de/buttons.js",
    "file"
  ],
  [
    "src/i18n/de/changelanguage.js",
    "file/src/i18n/de/changeLanguage.js.html",
    "src/i18n/de/changeLanguage.js",
    "file"
  ],
  [
    "src/i18n/de/changepassword.js",
    "file/src/i18n/de/changePassword.js.html",
    "src/i18n/de/changePassword.js",
    "file"
  ],
  [
    "src/i18n/de/common.js",
    "file/src/i18n/de/common.js.html",
    "src/i18n/de/common.js",
    "file"
  ],
  [
    "src/i18n/de/contactus.js",
    "file/src/i18n/de/contactUs.js.html",
    "src/i18n/de/contactUs.js",
    "file"
  ],
  [
    "src/i18n/de/faq.js",
    "file/src/i18n/de/faq.js.html",
    "src/i18n/de/faq.js",
    "file"
  ],
  [
    "src/i18n/de/index.js",
    "file/src/i18n/de/index.js.html",
    "src/i18n/de/index.js",
    "file"
  ],
  [
    "src/i18n/de/login.js",
    "file/src/i18n/de/login.js.html",
    "src/i18n/de/login.js",
    "file"
  ],
  [
    "src/i18n/de/myinfo.js",
    "file/src/i18n/de/myInfo.js.html",
    "src/i18n/de/myInfo.js",
    "file"
  ],
  [
    "src/i18n/de/mypass.js",
    "file/src/i18n/de/myPass.js.html",
    "src/i18n/de/myPass.js",
    "file"
  ],
  [
    "src/i18n/de/myprofile.js",
    "file/src/i18n/de/myProfile.js.html",
    "src/i18n/de/myProfile.js",
    "file"
  ],
  [
    "src/i18n/de/notifications.js",
    "file/src/i18n/de/notifications.js.html",
    "src/i18n/de/notifications.js",
    "file"
  ],
  [
    "src/i18n/de/results.js",
    "file/src/i18n/de/results.js.html",
    "src/i18n/de/results.js",
    "file"
  ],
  [
    "src/i18n/de/setting.js",
    "file/src/i18n/de/setting.js.html",
    "src/i18n/de/setting.js",
    "file"
  ],
  [
    "src/i18n/de/signup.js",
    "file/src/i18n/de/signup.js.html",
    "src/i18n/de/signup.js",
    "file"
  ],
  [
    "src/i18n/de/sitemanager.js",
    "file/src/i18n/de/siteManager.js.html",
    "src/i18n/de/siteManager.js",
    "file"
  ],
  [
    "src/i18n/de/terms.js",
    "file/src/i18n/de/terms.js.html",
    "src/i18n/de/terms.js",
    "file"
  ],
  [
    "src/i18n/en/about.js",
    "file/src/i18n/en/about.js.html",
    "src/i18n/en/about.js",
    "file"
  ],
  [
    "src/i18n/en/buttons.js",
    "file/src/i18n/en/buttons.js.html",
    "src/i18n/en/buttons.js",
    "file"
  ],
  [
    "src/i18n/en/changelanguage.js",
    "file/src/i18n/en/changeLanguage.js.html",
    "src/i18n/en/changeLanguage.js",
    "file"
  ],
  [
    "src/i18n/en/changepassword.js",
    "file/src/i18n/en/changePassword.js.html",
    "src/i18n/en/changePassword.js",
    "file"
  ],
  [
    "src/i18n/en/choosetest.js",
    "file/src/i18n/en/chooseTest.js.html",
    "src/i18n/en/chooseTest.js",
    "file"
  ],
  [
    "src/i18n/en/common.js",
    "file/src/i18n/en/common.js.html",
    "src/i18n/en/common.js",
    "file"
  ],
  [
    "src/i18n/en/confirmimage.js",
    "file/src/i18n/en/confirmImage.js.html",
    "src/i18n/en/confirmImage.js",
    "file"
  ],
  [
    "src/i18n/en/contactus.js",
    "file/src/i18n/en/contactUs.js.html",
    "src/i18n/en/contactUs.js",
    "file"
  ],
  [
    "src/i18n/en/faq.js",
    "file/src/i18n/en/faq.js.html",
    "src/i18n/en/faq.js",
    "file"
  ],
  [
    "src/i18n/en/forgotpassword.js",
    "file/src/i18n/en/forgotPassword.js.html",
    "src/i18n/en/forgotPassword.js",
    "file"
  ],
  [
    "src/i18n/en/index.js",
    "file/src/i18n/en/index.js.html",
    "src/i18n/en/index.js",
    "file"
  ],
  [
    "src/i18n/en/login.js",
    "file/src/i18n/en/login.js.html",
    "src/i18n/en/login.js",
    "file"
  ],
  [
    "src/i18n/en/modal.js",
    "file/src/i18n/en/modal.js.html",
    "src/i18n/en/modal.js",
    "file"
  ],
  [
    "src/i18n/en/myinfo.js",
    "file/src/i18n/en/myInfo.js.html",
    "src/i18n/en/myInfo.js",
    "file"
  ],
  [
    "src/i18n/en/mypass.js",
    "file/src/i18n/en/myPass.js.html",
    "src/i18n/en/myPass.js",
    "file"
  ],
  [
    "src/i18n/en/myprofile.js",
    "file/src/i18n/en/myProfile.js.html",
    "src/i18n/en/myProfile.js",
    "file"
  ],
  [
    "src/i18n/en/notifications.js",
    "file/src/i18n/en/notifications.js.html",
    "src/i18n/en/notifications.js",
    "file"
  ],
  [
    "src/i18n/en/results.js",
    "file/src/i18n/en/results.js.html",
    "src/i18n/en/results.js",
    "file"
  ],
  [
    "src/i18n/en/setimage.js",
    "file/src/i18n/en/setImage.js.html",
    "src/i18n/en/setImage.js",
    "file"
  ],
  [
    "src/i18n/en/setpassword.js",
    "file/src/i18n/en/setPassword.js.html",
    "src/i18n/en/setPassword.js",
    "file"
  ],
  [
    "src/i18n/en/setting.js",
    "file/src/i18n/en/setting.js.html",
    "src/i18n/en/setting.js",
    "file"
  ],
  [
    "src/i18n/en/signup.js",
    "file/src/i18n/en/signup.js.html",
    "src/i18n/en/signup.js",
    "file"
  ],
  [
    "src/i18n/en/sitemanager.js",
    "file/src/i18n/en/siteManager.js.html",
    "src/i18n/en/siteManager.js",
    "file"
  ],
  [
    "src/i18n/en/success.js",
    "file/src/i18n/en/success.js.html",
    "src/i18n/en/success.js",
    "file"
  ],
  [
    "src/i18n/en/terms.js",
    "file/src/i18n/en/terms.js.html",
    "src/i18n/en/terms.js",
    "file"
  ],
  [
    "src/i18n/en/verifyotp.js",
    "file/src/i18n/en/verifyOtp.js.html",
    "src/i18n/en/verifyOtp.js",
    "file"
  ],
  [
    "src/i18n/fr/about.js",
    "file/src/i18n/fr/about.js.html",
    "src/i18n/fr/about.js",
    "file"
  ],
  [
    "src/i18n/fr/buttons.js",
    "file/src/i18n/fr/buttons.js.html",
    "src/i18n/fr/buttons.js",
    "file"
  ],
  [
    "src/i18n/fr/changelanguage.js",
    "file/src/i18n/fr/changeLanguage.js.html",
    "src/i18n/fr/changeLanguage.js",
    "file"
  ],
  [
    "src/i18n/fr/changepassword.js",
    "file/src/i18n/fr/changePassword.js.html",
    "src/i18n/fr/changePassword.js",
    "file"
  ],
  [
    "src/i18n/fr/common.js",
    "file/src/i18n/fr/common.js.html",
    "src/i18n/fr/common.js",
    "file"
  ],
  [
    "src/i18n/fr/contactus.js",
    "file/src/i18n/fr/contactUs.js.html",
    "src/i18n/fr/contactUs.js",
    "file"
  ],
  [
    "src/i18n/fr/faq.js",
    "file/src/i18n/fr/faq.js.html",
    "src/i18n/fr/faq.js",
    "file"
  ],
  [
    "src/i18n/fr/index.js",
    "file/src/i18n/fr/index.js.html",
    "src/i18n/fr/index.js",
    "file"
  ],
  [
    "src/i18n/fr/login.js",
    "file/src/i18n/fr/login.js.html",
    "src/i18n/fr/login.js",
    "file"
  ],
  [
    "src/i18n/fr/myinfo.js",
    "file/src/i18n/fr/myInfo.js.html",
    "src/i18n/fr/myInfo.js",
    "file"
  ],
  [
    "src/i18n/fr/mypass.js",
    "file/src/i18n/fr/myPass.js.html",
    "src/i18n/fr/myPass.js",
    "file"
  ],
  [
    "src/i18n/fr/myprofile.js",
    "file/src/i18n/fr/myProfile.js.html",
    "src/i18n/fr/myProfile.js",
    "file"
  ],
  [
    "src/i18n/fr/notifications.js",
    "file/src/i18n/fr/notifications.js.html",
    "src/i18n/fr/notifications.js",
    "file"
  ],
  [
    "src/i18n/fr/results.js",
    "file/src/i18n/fr/results.js.html",
    "src/i18n/fr/results.js",
    "file"
  ],
  [
    "src/i18n/fr/setting.js",
    "file/src/i18n/fr/setting.js.html",
    "src/i18n/fr/setting.js",
    "file"
  ],
  [
    "src/i18n/fr/signup.js",
    "file/src/i18n/fr/signup.js.html",
    "src/i18n/fr/signup.js",
    "file"
  ],
  [
    "src/i18n/fr/sitemanager.js",
    "file/src/i18n/fr/siteManager.js.html",
    "src/i18n/fr/siteManager.js",
    "file"
  ],
  [
    "src/i18n/fr/terms.js",
    "file/src/i18n/fr/terms.js.html",
    "src/i18n/fr/terms.js",
    "file"
  ],
  [
    "src/i18n/index.js",
    "file/src/i18n/index.js.html",
    "src/i18n/index.js",
    "file"
  ],
  [
    "src/i18n/ja/about.js",
    "file/src/i18n/ja/about.js.html",
    "src/i18n/ja/about.js",
    "file"
  ],
  [
    "src/i18n/ja/buttons.js",
    "file/src/i18n/ja/buttons.js.html",
    "src/i18n/ja/buttons.js",
    "file"
  ],
  [
    "src/i18n/ja/changelanguage.js",
    "file/src/i18n/ja/changeLanguage.js.html",
    "src/i18n/ja/changeLanguage.js",
    "file"
  ],
  [
    "src/i18n/ja/changepassword.js",
    "file/src/i18n/ja/changePassword.js.html",
    "src/i18n/ja/changePassword.js",
    "file"
  ],
  [
    "src/i18n/ja/choosetest.js",
    "file/src/i18n/ja/chooseTest.js.html",
    "src/i18n/ja/chooseTest.js",
    "file"
  ],
  [
    "src/i18n/ja/common.js",
    "file/src/i18n/ja/common.js.html",
    "src/i18n/ja/common.js",
    "file"
  ],
  [
    "src/i18n/ja/confirmimage.js",
    "file/src/i18n/ja/confirmImage.js.html",
    "src/i18n/ja/confirmImage.js",
    "file"
  ],
  [
    "src/i18n/ja/contactus.js",
    "file/src/i18n/ja/contactUs.js.html",
    "src/i18n/ja/contactUs.js",
    "file"
  ],
  [
    "src/i18n/ja/faq.js",
    "file/src/i18n/ja/faq.js.html",
    "src/i18n/ja/faq.js",
    "file"
  ],
  [
    "src/i18n/ja/forgotpassword.js",
    "file/src/i18n/ja/forgotPassword.js.html",
    "src/i18n/ja/forgotPassword.js",
    "file"
  ],
  [
    "src/i18n/ja/index.js",
    "file/src/i18n/ja/index.js.html",
    "src/i18n/ja/index.js",
    "file"
  ],
  [
    "src/i18n/ja/login.js",
    "file/src/i18n/ja/login.js.html",
    "src/i18n/ja/login.js",
    "file"
  ],
  [
    "src/i18n/ja/modal.js",
    "file/src/i18n/ja/modal.js.html",
    "src/i18n/ja/modal.js",
    "file"
  ],
  [
    "src/i18n/ja/myinfo.js",
    "file/src/i18n/ja/myInfo.js.html",
    "src/i18n/ja/myInfo.js",
    "file"
  ],
  [
    "src/i18n/ja/mypass.js",
    "file/src/i18n/ja/myPass.js.html",
    "src/i18n/ja/myPass.js",
    "file"
  ],
  [
    "src/i18n/ja/myprofile.js",
    "file/src/i18n/ja/myProfile.js.html",
    "src/i18n/ja/myProfile.js",
    "file"
  ],
  [
    "src/i18n/ja/notifications.js",
    "file/src/i18n/ja/notifications.js.html",
    "src/i18n/ja/notifications.js",
    "file"
  ],
  [
    "src/i18n/ja/results.js",
    "file/src/i18n/ja/results.js.html",
    "src/i18n/ja/results.js",
    "file"
  ],
  [
    "src/i18n/ja/setimage.js",
    "file/src/i18n/ja/setImage.js.html",
    "src/i18n/ja/setImage.js",
    "file"
  ],
  [
    "src/i18n/ja/setpassword.js",
    "file/src/i18n/ja/setPassword.js.html",
    "src/i18n/ja/setPassword.js",
    "file"
  ],
  [
    "src/i18n/ja/setting.js",
    "file/src/i18n/ja/setting.js.html",
    "src/i18n/ja/setting.js",
    "file"
  ],
  [
    "src/i18n/ja/signup.js",
    "file/src/i18n/ja/signup.js.html",
    "src/i18n/ja/signup.js",
    "file"
  ],
  [
    "src/i18n/ja/sitemanager.js",
    "file/src/i18n/ja/siteManager.js.html",
    "src/i18n/ja/siteManager.js",
    "file"
  ],
  [
    "src/i18n/ja/success.js",
    "file/src/i18n/ja/success.js.html",
    "src/i18n/ja/success.js",
    "file"
  ],
  [
    "src/i18n/ja/terms.js",
    "file/src/i18n/ja/terms.js.html",
    "src/i18n/ja/terms.js",
    "file"
  ],
  [
    "src/i18n/ja/verifyotp.js",
    "file/src/i18n/ja/verifyOtp.js.html",
    "src/i18n/ja/verifyOtp.js",
    "file"
  ],
  [
    "src/i18n/ko/about.js",
    "file/src/i18n/ko/about.js.html",
    "src/i18n/ko/about.js",
    "file"
  ],
  [
    "src/i18n/ko/buttons.js",
    "file/src/i18n/ko/buttons.js.html",
    "src/i18n/ko/buttons.js",
    "file"
  ],
  [
    "src/i18n/ko/changelanguage.js",
    "file/src/i18n/ko/changeLanguage.js.html",
    "src/i18n/ko/changeLanguage.js",
    "file"
  ],
  [
    "src/i18n/ko/changepassword.js",
    "file/src/i18n/ko/changePassword.js.html",
    "src/i18n/ko/changePassword.js",
    "file"
  ],
  [
    "src/i18n/ko/choosetest.js",
    "file/src/i18n/ko/chooseTest.js.html",
    "src/i18n/ko/chooseTest.js",
    "file"
  ],
  [
    "src/i18n/ko/common.js",
    "file/src/i18n/ko/common.js.html",
    "src/i18n/ko/common.js",
    "file"
  ],
  [
    "src/i18n/ko/confirmimage.js",
    "file/src/i18n/ko/confirmImage.js.html",
    "src/i18n/ko/confirmImage.js",
    "file"
  ],
  [
    "src/i18n/ko/contactus.js",
    "file/src/i18n/ko/contactUs.js.html",
    "src/i18n/ko/contactUs.js",
    "file"
  ],
  [
    "src/i18n/ko/faq.js",
    "file/src/i18n/ko/faq.js.html",
    "src/i18n/ko/faq.js",
    "file"
  ],
  [
    "src/i18n/ko/forgotpassword.js",
    "file/src/i18n/ko/forgotPassword.js.html",
    "src/i18n/ko/forgotPassword.js",
    "file"
  ],
  [
    "src/i18n/ko/index.js",
    "file/src/i18n/ko/index.js.html",
    "src/i18n/ko/index.js",
    "file"
  ],
  [
    "src/i18n/ko/login.js",
    "file/src/i18n/ko/login.js.html",
    "src/i18n/ko/login.js",
    "file"
  ],
  [
    "src/i18n/ko/modal.js",
    "file/src/i18n/ko/modal.js.html",
    "src/i18n/ko/modal.js",
    "file"
  ],
  [
    "src/i18n/ko/myinfo.js",
    "file/src/i18n/ko/myInfo.js.html",
    "src/i18n/ko/myInfo.js",
    "file"
  ],
  [
    "src/i18n/ko/mypass.js",
    "file/src/i18n/ko/myPass.js.html",
    "src/i18n/ko/myPass.js",
    "file"
  ],
  [
    "src/i18n/ko/myprofile.js",
    "file/src/i18n/ko/myProfile.js.html",
    "src/i18n/ko/myProfile.js",
    "file"
  ],
  [
    "src/i18n/ko/notifications.js",
    "file/src/i18n/ko/notifications.js.html",
    "src/i18n/ko/notifications.js",
    "file"
  ],
  [
    "src/i18n/ko/results.js",
    "file/src/i18n/ko/results.js.html",
    "src/i18n/ko/results.js",
    "file"
  ],
  [
    "src/i18n/ko/setimage.js",
    "file/src/i18n/ko/setImage.js.html",
    "src/i18n/ko/setImage.js",
    "file"
  ],
  [
    "src/i18n/ko/setpassword.js",
    "file/src/i18n/ko/setPassword.js.html",
    "src/i18n/ko/setPassword.js",
    "file"
  ],
  [
    "src/i18n/ko/setting.js",
    "file/src/i18n/ko/setting.js.html",
    "src/i18n/ko/setting.js",
    "file"
  ],
  [
    "src/i18n/ko/signup.js",
    "file/src/i18n/ko/signup.js.html",
    "src/i18n/ko/signup.js",
    "file"
  ],
  [
    "src/i18n/ko/sitemanager.js",
    "file/src/i18n/ko/siteManager.js.html",
    "src/i18n/ko/siteManager.js",
    "file"
  ],
  [
    "src/i18n/ko/success.js",
    "file/src/i18n/ko/success.js.html",
    "src/i18n/ko/success.js",
    "file"
  ],
  [
    "src/i18n/ko/terms.js",
    "file/src/i18n/ko/terms.js.html",
    "src/i18n/ko/terms.js",
    "file"
  ],
  [
    "src/i18n/ko/verifyotp.js",
    "file/src/i18n/ko/verifyOtp.js.html",
    "src/i18n/ko/verifyOtp.js",
    "file"
  ],
  [
    "src/i18n/ru/about.js",
    "file/src/i18n/ru/about.js.html",
    "src/i18n/ru/about.js",
    "file"
  ],
  [
    "src/i18n/ru/changepassword.js",
    "file/src/i18n/ru/changePassword.js.html",
    "src/i18n/ru/changePassword.js",
    "file"
  ],
  [
    "src/i18n/ru/choosetest.js",
    "file/src/i18n/ru/chooseTest.js.html",
    "src/i18n/ru/chooseTest.js",
    "file"
  ],
  [
    "src/i18n/ru/common.js",
    "file/src/i18n/ru/common.js.html",
    "src/i18n/ru/common.js",
    "file"
  ],
  [
    "src/i18n/ru/confirmimage.js",
    "file/src/i18n/ru/confirmImage.js.html",
    "src/i18n/ru/confirmImage.js",
    "file"
  ],
  [
    "src/i18n/ru/contactus.js",
    "file/src/i18n/ru/contactUs.js.html",
    "src/i18n/ru/contactUs.js",
    "file"
  ],
  [
    "src/i18n/ru/faq.js",
    "file/src/i18n/ru/faq.js.html",
    "src/i18n/ru/faq.js",
    "file"
  ],
  [
    "src/i18n/ru/forgotpassword.js",
    "file/src/i18n/ru/forgotPassword.js.html",
    "src/i18n/ru/forgotPassword.js",
    "file"
  ],
  [
    "src/i18n/ru/index.js",
    "file/src/i18n/ru/index.js.html",
    "src/i18n/ru/index.js",
    "file"
  ],
  [
    "src/i18n/ru/login.js",
    "file/src/i18n/ru/login.js.html",
    "src/i18n/ru/login.js",
    "file"
  ],
  [
    "src/i18n/ru/modal.js",
    "file/src/i18n/ru/modal.js.html",
    "src/i18n/ru/modal.js",
    "file"
  ],
  [
    "src/i18n/ru/mypass.js",
    "file/src/i18n/ru/myPass.js.html",
    "src/i18n/ru/myPass.js",
    "file"
  ],
  [
    "src/i18n/ru/myprofile.js",
    "file/src/i18n/ru/myProfile.js.html",
    "src/i18n/ru/myProfile.js",
    "file"
  ],
  [
    "src/i18n/ru/results.js",
    "file/src/i18n/ru/results.js.html",
    "src/i18n/ru/results.js",
    "file"
  ],
  [
    "src/i18n/ru/setimage.js",
    "file/src/i18n/ru/setImage.js.html",
    "src/i18n/ru/setImage.js",
    "file"
  ],
  [
    "src/i18n/ru/setpassword.js",
    "file/src/i18n/ru/setPassword.js.html",
    "src/i18n/ru/setPassword.js",
    "file"
  ],
  [
    "src/i18n/ru/setting.js",
    "file/src/i18n/ru/setting.js.html",
    "src/i18n/ru/setting.js",
    "file"
  ],
  [
    "src/i18n/ru/signup.js",
    "file/src/i18n/ru/signup.js.html",
    "src/i18n/ru/signup.js",
    "file"
  ],
  [
    "src/i18n/ru/sitemanager.js",
    "file/src/i18n/ru/siteManager.js.html",
    "src/i18n/ru/siteManager.js",
    "file"
  ],
  [
    "src/i18n/ru/success.js",
    "file/src/i18n/ru/success.js.html",
    "src/i18n/ru/success.js",
    "file"
  ],
  [
    "src/i18n/ru/terms.js",
    "file/src/i18n/ru/terms.js.html",
    "src/i18n/ru/terms.js",
    "file"
  ],
  [
    "src/i18n/ru/verifyotp.js",
    "file/src/i18n/ru/verifyOtp.js.html",
    "src/i18n/ru/verifyOtp.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/about.js",
    "file/src/i18n/zh-hans/about.js.html",
    "src/i18n/zh-hans/about.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/buttons.js",
    "file/src/i18n/zh-hans/buttons.js.html",
    "src/i18n/zh-hans/buttons.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/changelanguage.js",
    "file/src/i18n/zh-hans/changeLanguage.js.html",
    "src/i18n/zh-hans/changeLanguage.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/changepassword.js",
    "file/src/i18n/zh-hans/changePassword.js.html",
    "src/i18n/zh-hans/changePassword.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/choosetest.js",
    "file/src/i18n/zh-hans/chooseTest.js.html",
    "src/i18n/zh-hans/chooseTest.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/common.js",
    "file/src/i18n/zh-hans/common.js.html",
    "src/i18n/zh-hans/common.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/confirmimage.js",
    "file/src/i18n/zh-hans/confirmImage.js.html",
    "src/i18n/zh-hans/confirmImage.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/contactus.js",
    "file/src/i18n/zh-hans/contactUs.js.html",
    "src/i18n/zh-hans/contactUs.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/faq.js",
    "file/src/i18n/zh-hans/faq.js.html",
    "src/i18n/zh-hans/faq.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/forgotpassword.js",
    "file/src/i18n/zh-hans/forgotPassword.js.html",
    "src/i18n/zh-hans/forgotPassword.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/index.js",
    "file/src/i18n/zh-hans/index.js.html",
    "src/i18n/zh-hans/index.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/login.js",
    "file/src/i18n/zh-hans/login.js.html",
    "src/i18n/zh-hans/login.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/modal.js",
    "file/src/i18n/zh-hans/modal.js.html",
    "src/i18n/zh-hans/modal.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/myinfo.js",
    "file/src/i18n/zh-hans/myInfo.js.html",
    "src/i18n/zh-hans/myInfo.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/mypass.js",
    "file/src/i18n/zh-hans/myPass.js.html",
    "src/i18n/zh-hans/myPass.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/myprofile.js",
    "file/src/i18n/zh-hans/myProfile.js.html",
    "src/i18n/zh-hans/myProfile.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/notifications.js",
    "file/src/i18n/zh-hans/notifications.js.html",
    "src/i18n/zh-hans/notifications.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/results.js",
    "file/src/i18n/zh-hans/results.js.html",
    "src/i18n/zh-hans/results.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/setimage.js",
    "file/src/i18n/zh-hans/setImage.js.html",
    "src/i18n/zh-hans/setImage.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/setpassword.js",
    "file/src/i18n/zh-hans/setPassword.js.html",
    "src/i18n/zh-hans/setPassword.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/setting.js",
    "file/src/i18n/zh-hans/setting.js.html",
    "src/i18n/zh-hans/setting.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/signup.js",
    "file/src/i18n/zh-hans/signup.js.html",
    "src/i18n/zh-hans/signup.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/sitemanager.js",
    "file/src/i18n/zh-hans/siteManager.js.html",
    "src/i18n/zh-hans/siteManager.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/success.js",
    "file/src/i18n/zh-hans/success.js.html",
    "src/i18n/zh-hans/success.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/terms.js",
    "file/src/i18n/zh-hans/terms.js.html",
    "src/i18n/zh-hans/terms.js",
    "file"
  ],
  [
    "src/i18n/zh-hans/verifyotp.js",
    "file/src/i18n/zh-hans/verifyOtp.js.html",
    "src/i18n/zh-hans/verifyOtp.js",
    "file"
  ],
  [
    "src/navigation/auth.js",
    "file/src/navigation/Auth.js.html",
    "src/navigation/Auth.js",
    "file"
  ],
  [
    "src/navigation/authenticated.js",
    "file/src/navigation/Authenticated.js.html",
    "src/navigation/Authenticated.js",
    "file"
  ],
  [
    "src/navigation/authenticatedtabnavigator.js",
    "file/src/navigation/AuthenticatedTabNavigator.js.html",
    "src/navigation/AuthenticatedTabNavigator.js",
    "file"
  ],
  [
    "src/navigation/commonstack.js",
    "file/src/navigation/CommonStack.js.html",
    "src/navigation/CommonStack.js",
    "file"
  ],
  [
    "src/navigation/resultsstack.js",
    "file/src/navigation/ResultsStack.js.html",
    "src/navigation/ResultsStack.js",
    "file"
  ],
  [
    "src/navigation/settingsstack.js",
    "file/src/navigation/SettingsStack.js.html",
    "src/navigation/SettingsStack.js",
    "file"
  ],
  [
    "src/navigation/sitemanagerstack.js",
    "file/src/navigation/SiteManagerStack.js.html",
    "src/navigation/SiteManagerStack.js",
    "file"
  ],
  [
    "src/redux/actions/user/index.js",
    "file/src/redux/actions/user/index.js.html",
    "src/redux/actions/user/index.js",
    "file"
  ],
  [
    "src/redux/reducers/user/index.js",
    "file/src/redux/reducers/user/index.js.html",
    "src/redux/reducers/user/index.js",
    "file"
  ],
  [
    "src/redux/store/index.js",
    "file/src/redux/store/index.js.html",
    "src/redux/store/index.js",
    "file"
  ],
  [
    "src/redux/type/index.js",
    "file/src/redux/type/index.js.html",
    "src/redux/type/index.js",
    "file"
  ],
  [
    "src/root/app.js",
    "file/src/root/App.js.html",
    "src/root/App.js",
    "file"
  ],
  [
    "src/screens/auth/confirmimage/index.js",
    "file/src/screens/auth/confirmImage/index.js.html",
    "src/screens/auth/confirmImage/index.js",
    "file"
  ],
  [
    "src/screens/auth/forgotpassword/index.js",
    "file/src/screens/auth/forgotPassword/index.js.html",
    "src/screens/auth/forgotPassword/index.js",
    "file"
  ],
  [
    "src/screens/auth/setpassword/index.js",
    "file/src/screens/auth/setPassword/index.js.html",
    "src/screens/auth/setPassword/index.js",
    "file"
  ],
  [
    "src/screens/auth/signup/index.js",
    "file/src/screens/auth/signUp/index.js.html",
    "src/screens/auth/signUp/index.js",
    "file"
  ],
  [
    "src/screens/auth/success/index.js",
    "file/src/screens/auth/success/index.js.html",
    "src/screens/auth/success/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/contactus/index.js",
    "file/src/screens/authenticated/contactUs/index.js.html",
    "src/screens/authenticated/contactUs/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/faq/index.js",
    "file/src/screens/authenticated/faq/index.js.html",
    "src/screens/authenticated/faq/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/myprofile/index.js",
    "file/src/screens/authenticated/myProfile/index.js.html",
    "src/screens/authenticated/myProfile/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/myprofile/tabs/index.js",
    "file/src/screens/authenticated/myProfile/tabs/index.js.html",
    "src/screens/authenticated/myProfile/tabs/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/index.js",
    "file/src/screens/authenticated/results/index.js.html",
    "src/screens/authenticated/results/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/confirmselftest/index.js",
    "file/src/screens/authenticated/results/selfTesting/confirmSelfTest/index.js.html",
    "src/screens/authenticated/results/selfTesting/confirmSelfTest/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen1.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen1.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen1.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen2.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen2.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen2.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen3.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen3.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen3.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen4.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen4.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen4.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen5.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen5.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen5.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen6.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen6.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen6.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen7.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen7.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen7.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/instructions/stintroscreen8.js",
    "file/src/screens/authenticated/results/selfTesting/instructions/STIntroScreen8.js.html",
    "src/screens/authenticated/results/selfTesting/instructions/STIntroScreen8.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/selftesting/takephotostart/index.js",
    "file/src/screens/authenticated/results/selfTesting/takePhotoStart/index.js.html",
    "src/screens/authenticated/results/selfTesting/takePhotoStart/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/results/success/index.js",
    "file/src/screens/authenticated/results/success/index.js.html",
    "src/screens/authenticated/results/success/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/success/index.js",
    "file/src/screens/authenticated/success/index.js.html",
    "src/screens/authenticated/success/index.js",
    "file"
  ],
  [
    "src/screens/authenticated/termsandconditions/index.js",
    "file/src/screens/authenticated/termsAndConditions/index.js.html",
    "src/screens/authenticated/termsAndConditions/index.js",
    "file"
  ],
  [
    "src/screens/common/loadingsplash/index.js",
    "file/src/screens/common/loadingSplash/index.js.html",
    "src/screens/common/loadingSplash/index.js",
    "file"
  ],
  [
    "src/utils/apirequests.js",
    "file/src/utils/apiRequests.js.html",
    "src/utils/apiRequests.js",
    "file"
  ],
  [
    "src/utils/asyncrequests.js",
    "file/src/utils/asyncRequests.js.html",
    "src/utils/asyncRequests.js",
    "file"
  ],
  [
    "src/utils/checkpermissions.js",
    "file/src/utils/checkPermissions.js.html",
    "src/utils/checkPermissions.js",
    "file"
  ],
  [
    "src/utils/detecttextlanguage.js",
    "file/src/utils/detectTextLanguage.js.html",
    "src/utils/detectTextLanguage.js",
    "file"
  ],
  [
    "src/utils/getbuilddetails.js",
    "file/src/utils/getBuildDetails.js.html",
    "src/utils/getBuildDetails.js",
    "file"
  ],
  [
    "src/utils/getdeviceinfo.js",
    "file/src/utils/getDeviceInfo.js.html",
    "src/utils/getDeviceInfo.js",
    "file"
  ],
  [
    "src/utils/numberformatting.js",
    "file/src/utils/numberFormatting.js.html",
    "src/utils/numberFormatting.js",
    "file"
  ],
  [
    "src/utils/react-redux-hooks.js",
    "file/src/utils/react-redux-hooks.js.html",
    "src/utils/react-redux-hooks.js",
    "file"
  ]
]